---
title: "Contributing guidelines"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Contributing guidelines}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# Contributing to `otargen`

This document outlines how to propose a change to the `otargen` package.

# Pull request process

-   We recommend that you create a Git branch for each pull request (PR).
-   We use [roxygen2](https://cran.r-project.org/web/packages/roxygen2/index.html), with [Markdown](https://roxygen2.r-lib.org/articles/rd-formatting.html) syntax, for documentation.
-   We use [testthat](https://cran.r-project.org/web/packages/testthat/index.html). Contributions with test cases included are easier to accept.
-   For user-facing changes, add a bullet to the top of NEWS.md below the current development version header describing the changes made followed by your GitHub username, and links to relevant issue(s)/PR(s).

# Prerequisites

Before you make a substantial pull request, you should always file an issue and make sure someone from the developer team agrees that it's a problem. If you've found a bug, create an associated [issue](https://github.com/amirfeizi/otargen/issues) and illustrate the bug.

# Code of Conduct

As contributors and maintainers of this project, we pledge to respect all people who contribute through reporting issues, posting feature requests, updating documentation, submitting pull requests or patches, and other activities.

We are committed to making participation in this project a harassment-free experience for everyone, regardless of level of experience, gender, gender identity and expression, sexual orientation, disability, personal appearance, body size, race, ethnicity, age, or religion.

Examples of unacceptable behavior by participants include the use of sexual language or imagery, derogatory comments or personal attacks, trolling, public or private harassment, insults, or other unprofessional conduct.

Project maintainers have the right and responsibility to remove, edit, or reject comments, commits, code, wiki edits, issues, and other contributions that are not aligned to this Code of Conduct. Project maintainers who do not follow the Code of Conduct may be removed from the project team.

Instances of abusive, harassing, or otherwise unacceptable behavior may be reported by opening an issue or contacting one or more of the project maintainers.

This Code of Conduct is adapted from the Contributor Covenant (<https://www.contributor-covenant.org/version/2/1/code_of_conduct/>)
